name: Upload Software to TIRA

on:
  workflow_dispatch:
    inputs:
      directory:
        description: "Root directory"
        required: true
        default: .

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install TIRA CLI
        run: |
          pip install --upgrade pip
          pip install tira

      - name: Submit to TIRA
        run: |
          tira-cli login --token ${{ secrets.TIRA_CLIENT_TOKEN }}
          tira-cli verify-installation \
          --task multi-author-writing-style-analysis-2026 \
          --team redblinkinglight
          tira-cli code-submission \
            --path ${{ inputs.directory }} \
            --task multi-author-writing-style-analysis-2026 \
            --dataset multi-author-writing-style-analysis-2026/smoketest-20260330-training
